// AUTO-GENERATED by scripts/buildDefinitions.ts — do not edit manually
// Run: bun run evidence:definitions:build
// ClinVar entries: 0  GWAS entries: 0  Total: 0

import type { GenericDefinitionParams } from "./evidencePack";

export const AUTO_DEFINITION_PARAMS: GenericDefinitionParams[] = [

];
