// AUTO-GENERATED by scripts/installEvidencePack.ts; do not edit manually.

export const LOCAL_EVIDENCE_PACK_VERSION = "2026-05-core-3";
export const LOCAL_EVIDENCE_PACK_BASE = `/evidence-packs/${LOCAL_EVIDENCE_PACK_VERSION}`;
